### PR TITLE
update message-schema version, fix unit tests and fix prettier CI

### PR DESCRIPTION
**Pull request by il3ven**
There is no release of @neume-network/message-schema corresponding to 0.0.1.

Check the versions tab here for more details. https://www.npmjs.com/package/@neume-network/message-schema

### CODE REVIEW

**Review by TimDaub — COMMENTED** [review]
GH Action looks indicate that neume-network/message-schema@0.2.0 is absent from package-lock.json. I'm expecting tests to succeed.

But I approve your change, so feel free to solve how you deem is best, I give u merge rights.

**Comment by il3ven** [comment]
Turns out there were multiple problems. These problems have been fixed:

- Updated `package-lock.json` because we use `npm ci` in GH actions.
- `@actions/checkout` was not able to execute. Fixed it by using default options.
- Fixed unit tests by updating message schema. Added `commissioner: "soundxyz"`. This change was prompted by this [commit](https://github.com/neume-network/message-schema/commit/3c21d92658f953d5894fef5eda6cfb7ab230f864) in message-schema.

**Comment by il3ven** [comment]
This PR is now not as simple as updating a package version. So, @TimDaub it would be good if you could review it once.

**Review by TimDaub — APPROVED** [review]
thanks for taking care of all of that! LGTM

**Pull request merged**
